### ISSUE TITLE
how do you exit vim?

### ISSUE THREAD

**Issue by groach** [alexbel/vim-config#1]

**Comment by seodma** [comment]
i'm also having this problem!

**Comment by carsonbland** [comment]
yes me too. it is very hard to exit

**Comment by carsonbland** [comment]
atom has ui.

**Comment by cleith** [comment]
Wtf is vim?

**Comment by carsonbland** [comment]
*better ui

**Comment by groach** [comment]
Everyone- if you restart computer, vim will exit

**Comment by mrhamric** [comment]
@groach been struggling with this for a while now. Any ideas?

**Comment by groach** [comment]
@mrhamric if you're on windows like i am you can hit ctrl+alt+delete and end the task. thats the best way i've found.

hopefully @alexbel will fix this bug!

**Comment by alexbel** [comment]
Hi guys.
It is a common and complex issue.
[The question on stackoverflow](https://stackoverflow.com/questions/11828270/how-to-exit-the-vim-editor) has reached 1000000 views. That means you are not alone.

The most common ways to exit vim:
![](https://s16.postimg.org/xoum0hsbp/exit_vim.jpg)

However I do not recommend that. As I said before quiting vim is a complex problem, so you should read this book and become a professional vim-quiter
![](https://s21.postimg.org/459h6lztj/exitingvim-big.png)

**Comment by groach** [comment]
Closing this issue. There is no fix.
